// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeLogs() {
  return window['go']['main']['App']['AnalyzeLogs']();
}

export function BackupDatabase(arg1) {
  return window['go']['main']['App']['BackupDatabase'](arg1);
}

export function CheckForUpdates(arg1) {
  return window['go']['main']['App']['CheckForUpdates'](arg1);
}

export function CleanCache() {
  return window['go']['main']['App']['CleanCache']();
}

export function CleanMSIOrphans(arg1) {
  return window['go']['main']['App']['CleanMSIOrphans'](arg1);
}

export function CompressCovers(arg1, arg2) {
  return window['go']['main']['App']['CompressCovers'](arg1, arg2);
}

export function FixUnicodeIssues() {
  return window['go']['main']['App']['FixUnicodeIssues']();
}

export function GetAvailableLanguages() {
  return window['go']['main']['App']['GetAvailableLanguages']();
}

export function GetCacheSize() {
  return window['go']['main']['App']['GetCacheSize']();
}

export function GetLibraryStats() {
  return window['go']['main']['App']['GetLibraryStats']();
}

export function GetMessages() {
  return window['go']['main']['App']['GetMessages']();
}

export function GetPlayStats() {
  return window['go']['main']['App']['GetPlayStats']();
}

export function GetPlaylistTracks(arg1) {
  return window['go']['main']['App']['GetPlaylistTracks'](arg1);
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetSyncableTracks() {
  return window['go']['main']['App']['GetSyncableTracks']();
}

export function HandleUTF8AlreadyEnabled() {
  return window['go']['main']['App']['HandleUTF8AlreadyEnabled']();
}

export function ID3AntiPiracyRestore(arg1) {
  return window['go']['main']['App']['ID3AntiPiracyRestore'](arg1);
}

export function ID3AntiPiracyV1(arg1) {
  return window['go']['main']['App']['ID3AntiPiracyV1'](arg1);
}

export function ID3AntiPiracyV2(arg1) {
  return window['go']['main']['App']['ID3AntiPiracyV2'](arg1);
}

export function ID3ClearAll(arg1) {
  return window['go']['main']['App']['ID3ClearAll'](arg1);
}

export function ID3ClearCover(arg1) {
  return window['go']['main']['App']['ID3ClearCover'](arg1);
}

export function ID3GetCover(arg1) {
  return window['go']['main']['App']['ID3GetCover'](arg1);
}

export function ID3PickDir() {
  return window['go']['main']['App']['ID3PickDir']();
}

export function ID3PickFile() {
  return window['go']['main']['App']['ID3PickFile']();
}

export function ID3ReadTag(arg1) {
  return window['go']['main']['App']['ID3ReadTag'](arg1);
}

export function ID3SetCover(arg1) {
  return window['go']['main']['App']['ID3SetCover'](arg1);
}

export function ID3WriteTag(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['ID3WriteTag'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function ListBackups() {
  return window['go']['main']['App']['ListBackups']();
}

export function ListDrives() {
  return window['go']['main']['App']['ListDrives']();
}

export function ListPlaylists() {
  return window['go']['main']['App']['ListPlaylists']();
}

export function MIDI2Disable() {
  return window['go']['main']['App']['MIDI2Disable']();
}

export function MIDI2Enable() {
  return window['go']['main']['App']['MIDI2Enable']();
}

export function MIDI2Status() {
  return window['go']['main']['App']['MIDI2Status']();
}

export function OpenDBDir() {
  return window['go']['main']['App']['OpenDBDir']();
}

export function OpenInstallDir() {
  return window['go']['main']['App']['OpenInstallDir']();
}

export function OpenLogsDir() {
  return window['go']['main']['App']['OpenLogsDir']();
}

export function OpenRegionSettings() {
  return window['go']['main']['App']['OpenRegionSettings']();
}

export function OpenRepository() {
  return window['go']['main']['App']['OpenRepository']();
}

export function OpenStemsDir() {
  return window['go']['main']['App']['OpenStemsDir']();
}

export function OptimizeDatabase() {
  return window['go']['main']['App']['OptimizeDatabase']();
}

export function Refresh() {
  return window['go']['main']['App']['Refresh']();
}

export function RemoveMissingTracks(arg1) {
  return window['go']['main']['App']['RemoveMissingTracks'](arg1);
}

export function RepairDatabase() {
  return window['go']['main']['App']['RepairDatabase']();
}

export function RestoreDatabase(arg1) {
  return window['go']['main']['App']['RestoreDatabase'](arg1);
}

export function RestoreUnicodeFix() {
  return window['go']['main']['App']['RestoreUnicodeFix']();
}

export function ScanMSIOrphans() {
  return window['go']['main']['App']['ScanMSIOrphans']();
}

export function ScanMissingTracks() {
  return window['go']['main']['App']['ScanMissingTracks']();
}

export function SelectDrive(arg1) {
  return window['go']['main']['App']['SelectDrive'](arg1);
}

export function SetLanguage(arg1) {
  return window['go']['main']['App']['SetLanguage'](arg1);
}

export function SyncBPMKeyToTags() {
  return window['go']['main']['App']['SyncBPMKeyToTags']();
}

export function USBUnlockAvailable() {
  return window['go']['main']['App']['USBUnlockAvailable']();
}

export function USBUnlockKill(arg1) {
  return window['go']['main']['App']['USBUnlockKill'](arg1);
}

export function USBUnlockScan(arg1) {
  return window['go']['main']['App']['USBUnlockScan'](arg1);
}
