// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {i18n} from '../models';
import {main} from '../models';
import {database} from '../models';
import {msi} from '../models';

export function BackupDatabase(arg1:string):Promise<string>;

export function CleanMSIOrphans(arg1:Array<string>):Promise<string>;

export function FixCJKIssues():Promise<string>;

export function GetAvailableLanguages():Promise<Array<Record<string, string>>>;

export function GetMessages():Promise<i18n.Messages>;

export function GetStatus():Promise<main.StatusInfo>;

export function HandleUTF8AlreadyEnabled():Promise<string>;

export function ListBackups():Promise<Array<database.BackupInfo>>;

export function ListDrives():Promise<Array<string>>;

export function OpenDBDir():Promise<string>;

export function OpenInstallDir():Promise<string>;

export function OpenRegionSettings():Promise<string>;

export function OpenRepository():Promise<void>;

export function OpenStemsDir():Promise<string>;

export function OptimizeDatabase():Promise<string>;

export function Refresh():Promise<main.StatusInfo>;

export function RestoreCJKFix():Promise<string>;

export function RestoreDatabase(arg1:string):Promise<string>;

export function ScanMSIOrphans():Promise<Array<msi.OrphanedMSI>>;

export function SelectDrive(arg1:string):Promise<string>;

export function SetLanguage(arg1:string):Promise<string>;
