// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FixCJKIssues() {
  return window['go']['main']['App']['FixCJKIssues']();
}

export function GetAvailableLanguages() {
  return window['go']['main']['App']['GetAvailableLanguages']();
}

export function GetMessages() {
  return window['go']['main']['App']['GetMessages']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function HandleUTF8AlreadyEnabled() {
  return window['go']['main']['App']['HandleUTF8AlreadyEnabled']();
}

export function OpenRegionSettings() {
  return window['go']['main']['App']['OpenRegionSettings']();
}

export function OpenRepository() {
  return window['go']['main']['App']['OpenRepository']();
}

export function Refresh() {
  return window['go']['main']['App']['Refresh']();
}

export function SetLanguage(arg1) {
  return window['go']['main']['App']['SetLanguage'](arg1);
}
