// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {logs} from '../models';
import {database} from '../models';
import {i18n} from '../models';
import {main} from '../models';
import {id3} from '../models';
import {msi} from '../models';
import {unlock} from '../models';

export function AnalyzeLogs():Promise<logs.LogStats>;

export function BackupDatabase(arg1:string):Promise<string>;

export function CheckForUpdates(arg1:string):Promise<Record<string, any>>;

export function CleanCache():Promise<string>;

export function CleanMSIOrphans(arg1:Array<string>):Promise<string>;

export function CompressCovers(arg1:number,arg2:number):Promise<Record<string, any>>;

export function FixUnicodeIssues():Promise<string>;

export function GetAvailableLanguages():Promise<Array<Record<string, string>>>;

export function GetCacheSize():Promise<number>;

export function GetLibraryStats():Promise<database.LibraryStats>;

export function GetMessages():Promise<i18n.Messages>;

export function GetPlayStats():Promise<database.PlayStats>;

export function GetPlaylistTracks(arg1:number):Promise<Array<database.TrackInfo>>;

export function GetStatus():Promise<main.StatusInfo>;

export function GetSyncableTracks():Promise<Array<database.SyncableTrack>>;

export function HandleUTF8AlreadyEnabled():Promise<string>;

export function ID3AntiPiracyRestore(arg1:string):Promise<string>;

export function ID3AntiPiracyV1(arg1:string):Promise<string>;

export function ID3AntiPiracyV2(arg1:string):Promise<string>;

export function ID3ClearAll(arg1:string):Promise<string>;

export function ID3ClearCover(arg1:string):Promise<string>;

export function ID3GetCover(arg1:string):Promise<string>;

export function ID3PickDir():Promise<string>;

export function ID3PickFile():Promise<string>;

export function ID3ReadTag(arg1:string):Promise<id3.TagInfo>;

export function ID3SetCover(arg1:string):Promise<string>;

export function ID3WriteTag(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<string>;

export function ListBackups():Promise<Array<database.BackupInfo>>;

export function ListDrives():Promise<Array<main.DriveInfo>>;

export function ListPlaylists():Promise<Array<database.PlaylistInfo>>;

export function MIDI2Disable():Promise<string>;

export function MIDI2Enable():Promise<string>;

export function MIDI2Status():Promise<string>;

export function OpenDBDir():Promise<string>;

export function OpenInstallDir():Promise<string>;

export function OpenLogsDir():Promise<string>;

export function OpenRegionSettings():Promise<string>;

export function OpenRepository():Promise<void>;

export function OpenStemsDir():Promise<string>;

export function OptimizeDatabase():Promise<string>;

export function Refresh():Promise<main.StatusInfo>;

export function RemoveMissingTracks(arg1:Array<number>):Promise<string>;

export function RepairDatabase():Promise<string>;

export function RestoreDatabase(arg1:string):Promise<string>;

export function RestoreUnicodeFix():Promise<string>;

export function ScanMSIOrphans():Promise<Array<msi.OrphanedMSI>>;

export function ScanMissingTracks():Promise<Array<database.MissingTrack>>;

export function SelectDrive(arg1:string):Promise<string>;

export function SetLanguage(arg1:string):Promise<string>;

export function SyncBPMKeyToTags():Promise<Record<string, any>>;

export function USBUnlockAvailable():Promise<string>;

export function USBUnlockKill(arg1:string):Promise<string>;

export function USBUnlockScan(arg1:string):Promise<Array<unlock.HandleInfo>>;
